name: GITHUB-CI

on:
  push:
    branches:
      - main
  # push_request:
  #   types: [opened]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [16, 18, 20]

    steps:
    - uses: actions/checkout@v4

    # - name: Setup node | ${{ matrix.node }}
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        # node-version: ${{ matrix.node }}
        node-version: 18
        cache: 'yarn'

    - run: yarn run

    - name: Semantic release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Generate tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      id: build-docker-image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        TAG: ${{ steps.generate_tag.outputs.sha }}
      run: |
        docker build -t $REGISTRY/rocketseat-rafael-ci:$TAG .
        docker push $REGISTRY/rocketseat-rafael-ci:$TAG
        docker tag $REGISTRY/rocketseat-rafael-ci:$TAG $REGISTRY/rocketseat-rafael-ci:latest
        docker push $REGISTRY/rocketseat-rafael-ci:latest
        IMAGE=$(echo $REGISTRY/rocketseat-rafael-ci:$TAG)
        echo "image=$IMAGE" >> $GITHUB_OUTPUT

    - name: Deploy to App Runner
      uses: awslabs/amazon-app-runner-deploy@main
      id: deploy-app-runner
      with:
        service: rocketseat-rafael-api
        image: ${{ steps.build-docker-image.outputs.image }}
        access-role-arn: ${{ secrets.AWS_APP_RUNNER_ROLE }}
        region: us-east-2
        cpu: 1
        memory: 2
        port: 3000
        wait-for-service-stability-seconds: 180

    - name: App Runner Check
      run: echo "App runner running... ${{ steps.deploy-app-runner.outputs.service-url }}"
